-- Supabase Database Schema for Parliament TV Integration
-- This schema defines the tables needed to store recognition results from Parliament TV

-- Table for storing Parliament TV videos
CREATE TABLE parliament_videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id INTEGER NOT NULL, -- ID from Parliament TV system
  title TEXT NOT NULL,
  description TEXT,
  capture_date TIMESTAMP WITH TIME ZONE,
  duration INTEGER, -- Duration in seconds
  combined_av_url TEXT, -- URL to the combined audio-video file
  status TEXT NOT NULL, -- Status of the recognition process (e.g., 'completed', 'processing')
  imported_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Add unique constraint on external_id to prevent duplicates
  CONSTRAINT unique_external_id UNIQUE (external_id)
);

-- Table for storing speaker appearances in videos
CREATE TABLE speaker_appearances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES parliament_videos(id) ON DELETE CASCADE,
  parliament_id TEXT, -- Parliament ID of the speaker (if available)
  name TEXT NOT NULL, -- Name of the speaker
  confidence REAL, -- Confidence score of the recognition (0-1)
  first_appearance INTEGER, -- First appearance timestamp in seconds
  last_appearance INTEGER, -- Last appearance timestamp in seconds
  total_time INTEGER, -- Total time the speaker appears in seconds
  appearances JSONB, -- Array of appearance intervals [{start: 123, end: 456}, ...]
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster queries on video_id
CREATE INDEX idx_speaker_appearances_video_id ON speaker_appearances(video_id);

-- Index for searching by parliament_id
CREATE INDEX idx_speaker_appearances_parliament_id ON speaker_appearances(parliament_id);

-- Function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add updated_at column and trigger to parliament_videos
ALTER TABLE parliament_videos ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE TRIGGER set_timestamp_parliament_videos
BEFORE UPDATE ON parliament_videos
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- Add updated_at column and trigger to speaker_appearances
ALTER TABLE speaker_appearances ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE TRIGGER set_timestamp_speaker_appearances
BEFORE UPDATE ON speaker_appearances
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- Create a view for video statistics
CREATE VIEW video_statistics AS
SELECT 
  pv.id AS video_id,
  pv.title,
  pv.capture_date,
  pv.duration,
  COUNT(sa.id) AS speaker_count,
  ARRAY_AGG(DISTINCT sa.name) AS speakers
FROM 
  parliament_videos pv
LEFT JOIN 
  speaker_appearances sa ON pv.id = sa.video_id
GROUP BY 
  pv.id, pv.title, pv.capture_date, pv.duration
ORDER BY 
  pv.capture_date DESC;

-- Create Row Level Security (RLS) policies
-- Enable RLS on tables
ALTER TABLE parliament_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE speaker_appearances ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Authenticated users can read parliament_videos"
  ON parliament_videos FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can read speaker_appearances"
  ON speaker_appearances FOR SELECT
  TO authenticated
  USING (true);

-- Create policies for service role (for API integration)
CREATE POLICY "Service role can insert parliament_videos"
  ON parliament_videos FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role can update parliament_videos"
  ON parliament_videos FOR UPDATE
  TO service_role
  USING (true);

CREATE POLICY "Service role can insert speaker_appearances"
  ON speaker_appearances FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role can update speaker_appearances"
  ON speaker_appearances FOR UPDATE
  TO service_role
  USING (true);

-- Comments for documentation
COMMENT ON TABLE parliament_videos IS 'Videos imported from Parliament TV with recognition results';
COMMENT ON TABLE speaker_appearances IS 'Speaker appearances detected in Parliament TV videos';
COMMENT ON COLUMN parliament_videos.external_id IS 'ID of the video in the Parliament TV system';
COMMENT ON COLUMN parliament_videos.combined_av_url IS 'URL to the combined audio-video file for playback';
COMMENT ON COLUMN speaker_appearances.parliament_id IS 'Parliament ID of the speaker if available';
COMMENT ON COLUMN speaker_appearances.appearances IS 'JSON array of appearance intervals with start and end times in seconds';
