create type public.app_role as enum ('admin', 'user');

create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null unique,
  role      app_role not null default 'user',
  email     text not null,
  is_first_login boolean not null default true,
  username text,
  stripe_customer_id text,
  stripe_account_id text,
  is_stripe_account_active boolean not null default false,
  is_online boolean not null default false,
  member_id INTEGER REFERENCES parliament_members(member_id) ON DELETE SET NULL,
  unique (user_id, role),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);
comment on table public.user_roles is 'Application roles for each user.';

create extension if not exists moddatetime schema extensions;
create trigger handle_updated_at before update on public.user_roles
  for each row execute procedure moddatetime('updated_at');

-- Grant necessary permissions
grant usage on schema public to postgres;
grant usage on schema public to supabase_auth_admin;
grant usage on schema public to service_role;

grant all on table public.user_roles to postgres;
grant all on table public.user_roles to supabase_auth_admin;
grant all on table public.user_roles to service_role;

alter table public.user_roles enable row level security;

create policy "Enable users to view their own data only"
on "public"."user_roles"
for select
to authenticated
using (
  (select auth.uid()) = user_id
);

-- Enable realtime for user_roles table
alter publication supabase_realtime add table public.user_roles;

-- Create function to set default role for new users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
    first_name text;
    last_name text;
    base_username text;
    new_username text;
    random_num integer;
    username_exists boolean;
BEGIN
    -- Extract first and last name from full_name
    first_name := split_part(NEW.raw_user_meta_data->>'full_name', ' ', 1);
    last_name := split_part(NEW.raw_user_meta_data->>'full_name', ' ', 2);
    
    -- If last name is empty, use first name only
    IF last_name = '' THEN
        base_username := lower(first_name);
    ELSE
        base_username := lower(first_name) || '-' || lower(last_name);
    END IF;
    
    -- Generate unique username with random number
    LOOP
        -- Generate random 4-digit number
        random_num := floor(random() * 9000 + 1000)::integer;
        new_username := base_username || '-' || random_num::text;
        
        -- Check if username exists
        SELECT EXISTS (
            SELECT 1 FROM public.user_roles WHERE user_roles.username = new_username
        ) INTO username_exists;
        
        -- Exit loop if username is unique
        EXIT WHEN NOT username_exists;
    END LOOP;
    
    -- Insert new user with generated username
    INSERT INTO public.user_roles (user_id, role, username, email)
    VALUES (NEW.id, 'user', new_username, NEW.email);
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to call function on user insert
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Grant execute permission on handle_new_user function
grant execute on function public.handle_new_user to postgres;
grant execute on function public.handle_new_user to supabase_auth_admin;
grant execute on function public.handle_new_user to service_role;