"""Update CaptureSession model

Revision ID: 5865d62460d8
Revises: bb7ae264ad0d
Create Date: 2025-04-26 12:26:16.071442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5865d62460d8'
down_revision: Union[str, None] = 'bb7ae264ad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_sessions_id'), 'capture_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_capture_sessions_status'), 'capture_sessions', ['status'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_clip_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_clip_id'], ['video_clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    op.create_index(op.f('ix_transcriptions_status'), 'transcriptions', ['status'], unique=False)
    op.add_column('social_posts', sa.Column('content', sa.String(), nullable=False))
    op.add_column('social_posts', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('social_posts', sa.Column('posted_time', sa.DateTime(), nullable=True))
    op.add_column('social_posts', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('social_posts', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('social_posts', sa.Column('video_clip_id', sa.Integer(), nullable=True))
    op.add_column('social_posts', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.alter_column('social_posts', 'platform',
               existing_type=postgresql.ENUM('TWITTER', 'FACEBOOK', 'INSTAGRAM', 'YOUTUBE', name='social_platform_enum'),
               type_=sa.Enum('TWITTER', 'FACEBOOK', 'INSTAGRAM', 'LINKEDIN', name='socialplatform'),
               existing_nullable=False)
    op.alter_column('social_posts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PUBLISHED', 'FAILED', name='post_status_enum'),
               type_=sa.Enum('DRAFT', 'SCHEDULED', 'POSTED', 'FAILED', name='poststatus'),
               nullable=True)
    op.alter_column('social_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('social_posts_clip_id_fkey', 'social_posts', type_='foreignkey')
    op.create_foreign_key(None, 'social_posts', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'social_posts', 'video_clips', ['video_clip_id'], ['id'])
    op.drop_column('social_posts', 'engagement_metrics')
    op.drop_column('social_posts', 'post_metadata')
    op.drop_column('social_posts', 'clip_id')
    op.drop_column('social_posts', 'post_url')
    op.drop_column('social_posts', 'post_id')
    op.drop_column('social_posts', 'posted_at')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MP', 'STAFF', name='user_role_enum'),
               type_=sa.Enum('ADMIN', 'MP', 'STAFF', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'STAFF'::user_role_enum"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'last_login')
    op.add_column('video_clips', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('video_clips', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('video_clips', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('video_clips', sa.Column('capture_session_id', sa.Integer(), nullable=True))
    op.alter_column('video_clips', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video_clips', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('video_clips', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED', name='clip_status_enum'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('video_clips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('video_clips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('video_clips', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('video_clips', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_video_clips_status'), 'video_clips', ['status'], unique=False)
    op.create_index(op.f('ix_video_clips_title'), 'video_clips', ['title'], unique=False)
    op.drop_constraint('video_clips_owner_id_fkey', 'video_clips', type_='foreignkey')
    op.create_foreign_key(None, 'video_clips', 'capture_sessions', ['capture_session_id'], ['id'])
    op.create_foreign_key(None, 'video_clips', 'users', ['user_id'], ['id'])
    op.drop_column('video_clips', 'source_url')
    op.drop_column('video_clips', 's3_key')
    op.drop_column('video_clips', 'faces_detected')
    op.drop_column('video_clips', 'owner_id')
    op.drop_column('video_clips', 'clip_metadata')
    op.drop_column('video_clips', 'transcription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('transcription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video_clips', sa.Column('clip_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('video_clips', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video_clips', sa.Column('faces_detected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('video_clips', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video_clips', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_clips', type_='foreignkey')
    op.drop_constraint(None, 'video_clips', type_='foreignkey')
    op.create_foreign_key('video_clips_owner_id_fkey', 'video_clips', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_video_clips_title'), table_name='video_clips')
    op.drop_index(op.f('ix_video_clips_status'), table_name='video_clips')
    op.alter_column('video_clips', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('video_clips', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('video_clips', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('video_clips', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('video_clips', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED', name='clip_status_enum'),
               nullable=False)
    op.alter_column('video_clips', 'duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_clips', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('video_clips', 'capture_session_id')
    op.drop_column('video_clips', 'user_id')
    op.drop_column('video_clips', 'error_message')
    op.drop_column('video_clips', 'storage_path')
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MP', 'STAFF', name='userrole'),
               type_=postgresql.ENUM('ADMIN', 'MP', 'STAFF', name='user_role_enum'),
               nullable=False,
               existing_server_default=sa.text("'STAFF'::user_role_enum"))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('social_posts', sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('post_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('post_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('clip_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('social_posts', sa.Column('post_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('engagement_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'social_posts', type_='foreignkey')
    op.drop_constraint(None, 'social_posts', type_='foreignkey')
    op.create_foreign_key('social_posts_clip_id_fkey', 'social_posts', 'video_clips', ['clip_id'], ['id'])
    op.alter_column('social_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_posts', 'status',
               existing_type=sa.Enum('DRAFT', 'SCHEDULED', 'POSTED', 'FAILED', name='poststatus'),
               type_=postgresql.ENUM('PENDING', 'PUBLISHED', 'FAILED', name='post_status_enum'),
               nullable=False)
    op.alter_column('social_posts', 'platform',
               existing_type=sa.Enum('TWITTER', 'FACEBOOK', 'INSTAGRAM', 'LINKEDIN', name='socialplatform'),
               type_=postgresql.ENUM('TWITTER', 'FACEBOOK', 'INSTAGRAM', 'YOUTUBE', name='social_platform_enum'),
               existing_nullable=False)
    op.drop_column('social_posts', 'created_by_id')
    op.drop_column('social_posts', 'video_clip_id')
    op.drop_column('social_posts', 'error_message')
    op.drop_column('social_posts', 'external_id')
    op.drop_column('social_posts', 'posted_time')
    op.drop_column('social_posts', 'scheduled_time')
    op.drop_column('social_posts', 'content')
    op.drop_index(op.f('ix_transcriptions_status'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_capture_sessions_status'), table_name='capture_sessions')
    op.drop_index(op.f('ix_capture_sessions_id'), table_name='capture_sessions')
    op.drop_table('capture_sessions')
    # ### end Alembic commands ###
