"""update models with named enums and constraints

Revision ID: bb7ae264ad0d
Revises: ba11c0baf518
Create Date: 2025-04-03 01:31:55.977963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb7ae264ad0d'
down_revision: Union[str, None] = 'ba11c0baf518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types first
    social_platform_enum = postgresql.ENUM('TWITTER', 'FACEBOOK', 'INSTAGRAM', 'YOUTUBE', name='social_platform_enum', create_type=False)
    social_platform_enum.create(op.get_bind(), checkfirst=True)

    post_status_enum = postgresql.ENUM('PENDING', 'PUBLISHED', 'FAILED', name='post_status_enum', create_type=False)
    post_status_enum.create(op.get_bind(), checkfirst=True)

    clip_status_enum = postgresql.ENUM('DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED', name='clip_status_enum', create_type=False)
    clip_status_enum.create(op.get_bind(), checkfirst=True)

    user_role_enum = postgresql.ENUM('ADMIN', 'MP', 'STAFF', name='user_role_enum', create_type=False)
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_posts', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('social_posts', sa.Column('engagement_metrics', sa.JSON(), nullable=True))
    op.add_column('social_posts', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('social_posts', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.alter_column('social_posts', 'clip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # Convert platform to lowercase before casting to enum
    op.execute("UPDATE social_posts SET platform = LOWER(platform)")
    op.execute("ALTER TABLE social_posts ALTER COLUMN platform TYPE social_platform_enum USING platform::social_platform_enum")
    op.alter_column('social_posts', 'platform', nullable=False)

    # Convert status to lowercase before casting to enum
    op.execute("UPDATE social_posts SET status = LOWER(status)")
    op.execute("ALTER TABLE social_posts ALTER COLUMN status TYPE post_status_enum USING status::post_status_enum")
    op.alter_column('social_posts', 'status', nullable=False)

    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='STAFF'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('video_clips', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('video_clips', sa.Column('faces_detected', sa.JSON(), nullable=True))
    op.alter_column('video_clips', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('video_clips', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('video_clips', 'start_time',
               existing_type=sa.DateTime(),
               nullable=False)
    op.alter_column('video_clips', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Convert status to lowercase before casting to enum
    op.execute("UPDATE video_clips SET status = LOWER(status)")
    op.execute("ALTER TABLE video_clips ALTER COLUMN status TYPE clip_status_enum USING status::clip_status_enum")
    op.alter_column('video_clips', 'status', nullable=False)

    op.alter_column('video_clips', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_clips', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_clips', 'status',
               existing_type=clip_status_enum,
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video_clips', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_clips', 'start_time',
               existing_type=sa.DateTime(),
               nullable=True)
    op.alter_column('video_clips', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video_clips', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('video_clips', 'faces_detected')
    op.drop_column('video_clips', 'end_time')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'role')
    op.alter_column('social_posts', 'status',
               existing_type=post_status_enum,
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('social_posts', 'platform',
               existing_type=social_platform_enum,
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('social_posts', 'clip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('social_posts', 'updated_at')
    op.drop_column('social_posts', 'created_at')
    op.drop_column('social_posts', 'engagement_metrics')
    op.drop_column('social_posts', 'post_url')

    # Drop enum types
    social_platform_enum.drop(op.get_bind(), checkfirst=True)
    post_status_enum.drop(op.get_bind(), checkfirst=True)
    clip_status_enum.drop(op.get_bind(), checkfirst=True)
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
